config/routes.rb
Rails.application.routes.draw do
  

  root 'welcome#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :users do
    resource :profile
    resources :lists do
      resources :items
    end
  end

  resources :friendships

  get '/my_requests' => "friendships#my_requests", :as => "aloha"
  post "/accept_friendship" => "friendships#accept_friendship"
  delete "/reject_friendship" => "friendships#reject_friendship"
  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  before_save :default_values
  
  # validates_uniqueness_of [:user_id, :friend_id]
  validates_uniqueness_of :user_id, :scope => [:friend_id,]

  def default_values
    self.status ||= "request"
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates :todo, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
  def index
    # friendships = Friendship.where(user_id: current_user.id, status: "active")
    # friendships2 = Friendship.where(friend_id: current_user.id, status: "active")
    # @friends = []
    # friendships.each do |friendship|
    #   @friends << User.find(friendship.friend_id)
    # end
    # friendships2.each do |friendship|
    #   @friends << User.find(friendship.user_id)
    # end
    friendships = Friendship.where(user_id: current_user.id, status: "active")
    @friends = User.where(id: friendships.map(&:friend_id))

    @incoming_requests = Friendship.where(friend_id: current_user.id, status: "request")
  end

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:user])
    unless Friendship.exists?(:user_id => @friendship.friend_id, :friend_id => current_user.id)
      if @friendship.save
        flash[:notice] = "request has been sent."
        redirect_to root_url
      else
        flash[:notice] = "Unable to add friend."
        redirect_to users_path
      end
    else
      flash[:notice] = "This user has already sent you request. You can confirm or reject it in your incoming requests"
      redirect_to users_path
    end
  end

  # def update
  #   @friendship = Friendship.find
  # end

  def my_requests
    @incoming_requests = Friendship.where(friend_id: current_user.id, status: "request")
  end

  def accept_friendship
    @friendship = Friendship.find(params[:id])
    @friendship.status = "active"
    if @friendship.save
      Friendship.create(:user_id => @friendship.friend_id, :friend_id => @friendship.user_id, :status => "active")
      redirect_to friendships_path
    end
  end

  def reject_friendship
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
    redirect_to friendships_path
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index

  end

  def create
    @list = current_user.lists.find(params[:list_id])
    @item = @list.items.new(items_param)

    respond_to do |format|
      if @item.save
        format.html {redirect_to user_list_path(current_user, @list)}
        format.js
      end
    end
  end

  def destroy
    @list = current_user.lists.find(params[:list_id])
    @item = @list.items.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html {redirect_to user_list_path(current_user, current_user)}
      format.js
    end
  end



  private

  def items_param
    params.require(:item).permit(:todo)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = current_user.lists.all
    @list = List.new

    respond_to do |format|
      format.html # index.html.erb
      format.json {render :json => {:lists => @lists, :user => current_user} }
    end
    
  end

  def show
    @list  = current_user.lists.find(params[:id])
    @items = @list.items.all
    @item  = Item.new
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @lists = current_user.lists.all
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to user_list_path(current_user, @list) }
        format.js
      end
    end  
  end

  def update
    @list = current_user.lists.find(params[:id])


    if @list.update_attributes(list_params)
      render json: @list.to_json(only: :title)
    else
      render 'show'
    end
  end

  def destroy
    @lists = current_user.lists.all
    @list = current_user.lists.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to action: :index }
      format.js
    end 

    
    
  end

  private

    def list_params
      params.require(:list).permit(:title)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:user_id])
  end

  def edit
    @user = current_user
    @profile = @user.profile
  end

  def update
    @user = current_user

    if @user.profile.update_attributes(profile_params)
      redirect_to user_profile_path
    end
  end

  private

    def profile_params
      params.require(:profile).permit(:name, :surname, :age, :genre)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    build_resource({})
    self.resource.profile = Profile.new
    respond_with self.resource
  end
 
  private

  def sign_up_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation, profile_attributes: [:name, :surname, :age, :genre])
  end

  def account_update_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toto_items_helper.rb
module TotoItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/index.html.erb
<h1>Friends</h1>
<% @friends.each do |friend| %>
  <p><%= link_to friend.profile.name, user_profile_path(friend.id) %></p>
<% end %>
<%= link_to "requests", aloha_path %>(<%= @incoming_requests.count %>)

app/views/friendships/my_requests.html.erb
<h1>Incoming requests(<%= @incoming_requests.count %>)</h1>
<ul>
  <% @incoming_requests.each do |request| %>
    <li><%= request.user.profile.name %> - <%= link_to "accept", accept_friendship_path(id: request.id), method: :post %> | <%= link_to "no, thanks", reject_friendship_path(id: request.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/items/_items.html.erb
<h2>You have <span class="items_counter"><%= pluralize(@items.size, "todo item") %></span></h2>
<ul class="all_items">
  <% @items.each do |item| %>
    <li id="li_item_<%= item.id %>"><%= item.todo %><%= link_to "delete", [current_user, @list, item], remote: true, method: :delete %></li>
  <% end %>
</ul>

app/views/items/create.js.erb
$(".all_items").append('<li id="li_item_<%= @item.id %>"><%= @item.todo %><%= link_to "delete", [current_user, @list, @item], remote: true, method: :delete %></li>');

var count_items = parseInt($(".items_counter").html()) + 1;
var new_count = count_items == 1 ? count_items + " todo item" : count_items + " todo items";
$(".items_counter").html(new_count);

app/views/items/destroy.js.erb
$("#li_item_<%= @item.id %>").remove();

var count_items = parseInt($(".items_counter").html()) - 1;
var new_count = count_items == 1 ? count_items + " todo item" : count_items + " todo items";
$(".items_counter").html(new_count);

app/views/lists/_form_list.html.erb
<%= form_for @list, url: user_lists_path, remote: true do |f| %>
  <%= f.text_field :title, placeholder: "Enter title" %>
  <%= f.submit "save", class: "new_list_btn" %>
<% end %>
<p class="error-message" style="color: red;"><%= @list.errors.full_messages.first if @list.errors.any? %></p>

app/views/lists/_list.html.erb
<li id="list_<%= partial_list.id %>">
  <%= link_to partial_list.title, user_list_path(current_user, partial_list), class: "show_list"%>
  <%= link_to "remove", user_list_path(current_user, partial_list), method: :delete, remote: true, class: "remove_list" %>
</li>

app/views/lists/create.js.erb
$("#new_list").remove();
$("#add_new_list").show();
$('.all_lists').append("<%= j render 'list', partial_list: @list %>");


// $('.all_lists').append('<li id="list_<%= @list.id %>" ><%= link_to @list.title, user_list_path(current_user, @list) %> <%= link_to "(remove)", user_list_path(current_user, @list), method: :delete, remote: true, class: "remove_list" %></li>');


$(".lists_counter_title").html('Item has been added<br/>Now you have <%= pluralize(@lists.size, "item") %>');

app/views/lists/destroy.js.erb
$('#list_<%= @list.id %>').remove();
$(".lists_counter_title").html('Item has been removed<br/>Now you have <%= pluralize(@lists.size, "item") %>');

app/views/lists/index.html.erb
<h2 class="lists_counter_title">You have <%= pluralize(@lists.size, "item") %></h2>

<ul class="all_lists">
  <% @lists.each do |list| %>
    <li id="list_<%= list.id %>">
      <%= link_to list.title, user_list_path(current_user, list), class: "show_list" %>
      <%= link_to "remove", user_list_path(current_user, list), method: :delete, remote: true, class: "remove_list" %>
    </li>
  <% end %>
</ul>
<%= link_to "Add new list", new_user_list_path(current_user), id: "add_new_list", remote: true %>

app/views/lists/new.html.erb
<h1>Create new List</h1>
<%= form_for @list, url: user_lists_path do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "save", class: "new_list_btn" %>
<% end %>
<p class="error-message" style="color: red;"><%= @list.errors.full_messages.first if @list.errors.any? %></p>

app/views/lists/new.js.erb
$("#add_new_list").hide().after("<%= j render('form_list') %>");

app/views/lists/show.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
 
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h2 class="list_header"><%= @list.title %></h2> <span id="update_list_litle">(update)</span>
<div class="edit-list-form">
  <%= form_for [current_user, @list], method: 'put' do |f| %>
    <%= f.text_field :title %>
    <%= f.submit "Update list title", :class => "btn-title-upd", :disabled => true %>
  <% end %>
</div>

<%= form_for [current_user, @list, @item], remote: true do |f| %> 
  <%= f.text_field :todo, placeholder: "What to do?" %>
  <%= f.submit "Add item", :class => "btn-add-item", :disabled => true %>
<% end %>

<%= render partial: "items/items" %>

<div class="time">
  <p>Created: <%= @list.created_at %></p>
  <p>Last updated: <%= @list.updated_at %></p>
</div>


<%= link_to 'delete this list', [current_user, @list], method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn-list-delete" %>
<%= link_to "see my all lists", user_lists_path %>
<%= link_to "create new list", new_user_list_path %>

app/views/profiles/edit.html.erb
<h2>Edit Profile<h2>
<%= form_for :profile, url: user_profile_path, method: "PUT" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :surname %>
  <%= f.text_field :surname %><br />
  <%= f.label :age %>
  <%= f.text_field :age %><br />
  <%= f.label :genre_male, "Male" %>
  <%= f.radio_button :genre, 'male' %>
  <%= f.label :genre_female, "Female" %>
  <%= f.radio_button :genre, 'female' %><br />
  <%= f.submit "Save" %>
<% end %>

app/views/profiles/show.html.erb
<h1>My Profile</h1>
<div>
  <b>Name:</b> <%= @user.profile.name %><br />
  <b>Surname:</b> <%= @user.profile.surname %><br />
  <b>Email:</b> <%= @user.email %><br />
  <b>Login:</b> <%= @user.login %><br />
  <b>Age:</b> <%= @user.profile.age %><br />
  <b>Genge:</b> <%= @user.profile.genre %><br />
</div>

<%= link_to "Edit registration data", edit_user_registration_path %>
<%= link_to "Edit Profile data", edit_user_profile_path %>
<%= link_to "My friends", friendships_path %>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>

<table>
  <tr><th>Name</th><th>email</th></tr>
    <% @users.each do |user| %>
      <% unless user.id == current_user.id %>
        <tr>
          <td><%= user.profile.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "add to friend", friendships_path(:user => user.id), :method => "Post" %></td>
        </tr>
      <% end %>
    <% end %>
</table>

app/views/welcome/_navigation.html.erb
<% content_for :navigation do %>
  <%= link_to "Main page", root_path, :title => "Main page" %>
  <%= link_to "my lists", user_lists_path(@user) %>
  <%= link_to "My Profile", user_profile_path(@user.id) %>
  <%= link_to "Users", users_path %>
  <%= link_to "Friends", friendships_path %>
<% end %>

app/views/welcome/index.html.erb
<% if @user %>
  <h1>Hello <%= @user.login %></h1>
  <%= render "navigation" %>
<% end %>